# Generated by Django 5.2.16 on 2026-07-23 09:30

import apps.wallpapers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('icon_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('accent_color', models.CharField(blank=True, max_length=9, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, validators=[apps.wallpapers.models.validate_tag_slug])),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallpapers.collection')),
            ],
            options={
                'ordering': ['collection', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('square', 'Square')], max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('preview_video_url', models.URLField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField()),
                ('license_type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='published', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallpapers', to='wallpapers.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='wallpapers', through='wallpapers.CollectionItem', to='wallpapers.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='wallpapers', to='wallpapers.tag')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='wallpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='wallpapers.wallpaper'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['-created_at', '-id'], name='wp_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['is_premium'], name='wp_is_premium_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['deleted_at'], name='wp_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'wallpaper'), name='uniq_collection_wallpaper'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'position'), name='uniq_collection_position'),
        ),
    ]
