# Generated by Django 5.2.16 on 2026-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='preview_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='source_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
