# Generated by Django 5.2.16 on 2026-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_widen_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='master_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='preview_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='staging_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
