# Generated by Django 5.2.16 on 2026-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0003_wallpaper_failure_reason_wallpaper_master_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='home_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['show_on_home', 'home_position', 'id'], name='coll_home_idx'),
        ),
    ]
