# Generated by Django 5.2.16 on 2026-07-26 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS (App Store)'), ('android', 'Android (Google Play)')], max_length=10)),
                ('store_event_id', models.CharField(max_length=255)),
                ('notification_type', models.CharField(max_length=120)),
                ('original_transaction_id', models.CharField(blank=True, max_length=255)),
                ('store_event_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('duplicate_ignored', 'Duplicate ignored'), ('stale_ignored', 'Stale / out-of-order ignored'), ('unmatched', 'Unmatched (no entitlement)')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['original_transaction_id'], name='iap_notif_original_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'store_event_id'), name='iap_notif_event_unique')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS (App Store)'), ('android', 'Android (Google Play)')], max_length=10)),
                ('original_transaction_id', models.CharField(max_length=255)),
                ('latest_transaction_id', models.CharField(blank=True, max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_grace_period', 'In grace period / billing retry'), ('expired', 'Expired'), ('canceled', 'Canceled (lapsed)'), ('refunded', 'Refunded')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('origin_device_id', models.CharField(blank=True, max_length=255)),
                ('last_store_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'original_transaction_id'], name='iap_ent_original_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'original_transaction_id'), name='iap_entitlement_unique_original_txn')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS (App Store)'), ('android', 'Android (Google Play)')], max_length=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='iap.subscriptionentitlement')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'transaction_id'], name='iap_txn_ref_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'transaction_id'), name='iap_txn_ref_unique')],
            },
        ),
    ]
